package com.drew.metadata.mov.metadata;

import androidx.exifinterface.media.ExifInterface;
import com.brentvatne.react.ReactVideoViewManager;
import com.drew.lang.annotations.NotNull;
import com.drew.metadata.exif.makernotes.LeicaType5MakernoteDirectory;
import com.drew.metadata.exif.makernotes.OlympusCameraSettingsMakernoteDirectory;
import com.drew.metadata.exif.makernotes.SonyType6MakernoteDirectory;
import com.drew.metadata.mov.QuickTimeDirectory;
import com.drew.metadata.photoshop.PhotoshopDirectory;
import java.util.HashMap;

public class QuickTimeMetadataDirectory extends QuickTimeDirectory {
    @NotNull
    protected static final HashMap<String, Integer> _tagIntegerMap = new HashMap();
    @NotNull
    protected static final HashMap<Integer, String> _tagNameMap = new HashMap();

    @NotNull
    public String getName() {
        return "QuickTime Metadata";
    }

    public QuickTimeMetadataDirectory() {
        setDescriptor(new QuickTimeMetadataDescriptor(this));
    }

    static {
        HashMap hashMap = _tagIntegerMap;
        Integer valueOf = Integer.valueOf(OlympusCameraSettingsMakernoteDirectory.TagWhiteBalance2);
        hashMap.put("com.apple.quicktime.album", valueOf);
        hashMap = _tagIntegerMap;
        Integer valueOf2 = Integer.valueOf(OlympusCameraSettingsMakernoteDirectory.TagWhiteBalanceTemperature);
        hashMap.put("com.apple.quicktime.artist", valueOf2);
        hashMap = _tagIntegerMap;
        Integer valueOf3 = Integer.valueOf(OlympusCameraSettingsMakernoteDirectory.TagWhiteBalanceBracket);
        hashMap.put("com.apple.quicktime.artwork", valueOf3);
        hashMap = _tagIntegerMap;
        Integer valueOf4 = Integer.valueOf(OlympusCameraSettingsMakernoteDirectory.TagCustomSaturation);
        hashMap.put("com.apple.quicktime.author", valueOf4);
        hashMap = _tagIntegerMap;
        Integer valueOf5 = Integer.valueOf(OlympusCameraSettingsMakernoteDirectory.TagModifiedSaturation);
        hashMap.put("com.apple.quicktime.comment", valueOf5);
        hashMap = _tagIntegerMap;
        Integer valueOf6 = Integer.valueOf(OlympusCameraSettingsMakernoteDirectory.TagContrastSetting);
        hashMap.put("com.apple.quicktime.copyright", valueOf6);
        hashMap = _tagIntegerMap;
        Integer valueOf7 = Integer.valueOf(OlympusCameraSettingsMakernoteDirectory.TagSharpnessSetting);
        hashMap.put("com.apple.quicktime.creationdate", valueOf7);
        _tagIntegerMap.put("com.apple.quicktime.description", Integer.valueOf(OlympusCameraSettingsMakernoteDirectory.TagColorSpace));
        _tagIntegerMap.put("com.apple.quicktime.director", Integer.valueOf(1288));
        _tagIntegerMap.put("com.apple.quicktime.title", Integer.valueOf(OlympusCameraSettingsMakernoteDirectory.TagSceneMode));
        _tagIntegerMap.put("com.apple.quicktime.genre", Integer.valueOf(OlympusCameraSettingsMakernoteDirectory.TagNoiseReduction));
        _tagIntegerMap.put("com.apple.quicktime.information", Integer.valueOf(OlympusCameraSettingsMakernoteDirectory.TagDistortionCorrection));
        _tagIntegerMap.put("com.apple.quicktime.keywords", Integer.valueOf(OlympusCameraSettingsMakernoteDirectory.TagShadingCompensation));
        _tagIntegerMap.put("com.apple.quicktime.location.ISO6709", Integer.valueOf(OlympusCameraSettingsMakernoteDirectory.TagCompressionFactor));
        _tagIntegerMap.put("com.apple.quicktime.producer", Integer.valueOf(1294));
        _tagIntegerMap.put("com.apple.quicktime.publisher", Integer.valueOf(OlympusCameraSettingsMakernoteDirectory.TagGradation));
        _tagIntegerMap.put("com.apple.quicktime.software", Integer.valueOf(1296));
        _tagIntegerMap.put("com.apple.quicktime.year", Integer.valueOf(1297));
        _tagIntegerMap.put("com.apple.quicktime.collection.user", Integer.valueOf(1298));
        _tagIntegerMap.put("com.apple.quicktime.rating.user", Integer.valueOf(SonyType6MakernoteDirectory.TAG_MAKERNOTE_THUMB_OFFSET));
        _tagIntegerMap.put("com.apple.quicktime.location.name", Integer.valueOf(SonyType6MakernoteDirectory.TAG_MAKERNOTE_THUMB_LENGTH));
        _tagIntegerMap.put("com.apple.quicktime.location.body", Integer.valueOf(1301));
        _tagIntegerMap.put("com.apple.quicktime.location.note", Integer.valueOf(1302));
        _tagIntegerMap.put("com.apple.quicktime.location.role", Integer.valueOf(1303));
        _tagIntegerMap.put("com.apple.quicktime.location.date", Integer.valueOf(1304));
        _tagIntegerMap.put("com.apple.quicktime.direction.facing", Integer.valueOf(1305));
        _tagIntegerMap.put("com.apple.quicktime.direction.motion", Integer.valueOf(1306));
        _tagIntegerMap.put("com.apple.quicktime.displayname", Integer.valueOf(1307));
        _tagIntegerMap.put("com.apple.quicktime.content.identifier", Integer.valueOf(1308));
        _tagIntegerMap.put("com.apple.quicktime.make", Integer.valueOf(1309));
        _tagIntegerMap.put("com.apple.quicktime.model", Integer.valueOf(1310));
        _tagIntegerMap.put("com.apple.photos.originating.signature", Integer.valueOf(1311));
        _tagIntegerMap.put("----", Integer.valueOf(1024));
        _tagIntegerMap.put("@PST", Integer.valueOf(1025));
        _tagIntegerMap.put("@ppi", Integer.valueOf(PhotoshopDirectory.TAG_LAYERS_GROUP_INFORMATION));
        _tagIntegerMap.put("@pti", Integer.valueOf(1027));
        _tagIntegerMap.put("@sti", Integer.valueOf(1028));
        _tagIntegerMap.put("AACR", Integer.valueOf(1029));
        _tagIntegerMap.put("CDEK", Integer.valueOf(1030));
        _tagIntegerMap.put("CDET", Integer.valueOf(LeicaType5MakernoteDirectory.TagOriginalFileName));
        _tagIntegerMap.put("GUID", Integer.valueOf(1032));
        _tagIntegerMap.put("VERS", Integer.valueOf(PhotoshopDirectory.TAG_THUMBNAIL_OLD));
        _tagIntegerMap.put("aART", Integer.valueOf(PhotoshopDirectory.TAG_COPYRIGHT));
        _tagIntegerMap.put("akID", Integer.valueOf(PhotoshopDirectory.TAG_URL));
        _tagIntegerMap.put("albm", Integer.valueOf(PhotoshopDirectory.TAG_THUMBNAIL));
        _tagIntegerMap.put("apID", Integer.valueOf(1037));
        _tagIntegerMap.put("atID", Integer.valueOf(1038));
        _tagIntegerMap.put("auth", Integer.valueOf(PhotoshopDirectory.TAG_ICC_PROFILE_BYTES));
        _tagIntegerMap.put("catg", Integer.valueOf(1040));
        _tagIntegerMap.put("cnID", Integer.valueOf(PhotoshopDirectory.TAG_ICC_UNTAGGED_PROFILE));
        _tagIntegerMap.put("covr", Integer.valueOf(1042));
        _tagIntegerMap.put("cpil", Integer.valueOf(1043));
        _tagIntegerMap.put("cprt", Integer.valueOf(PhotoshopDirectory.TAG_SEED_NUMBER));
        _tagIntegerMap.put("desc", Integer.valueOf(PhotoshopDirectory.TAG_UNICODE_ALPHA_NAMES));
        _tagIntegerMap.put("disk", Integer.valueOf(PhotoshopDirectory.TAG_INDEXED_COLOR_TABLE_COUNT));
        _tagIntegerMap.put("dscp", Integer.valueOf(PhotoshopDirectory.TAG_TRANSPARENCY_INDEX));
        _tagIntegerMap.put("egid", Integer.valueOf(1048));
        _tagIntegerMap.put("geID", Integer.valueOf(PhotoshopDirectory.TAG_GLOBAL_ALTITUDE));
        _tagIntegerMap.put("gnre", Integer.valueOf(PhotoshopDirectory.TAG_SLICES));
        _tagIntegerMap.put("grup", Integer.valueOf(PhotoshopDirectory.TAG_WORKFLOW_URL));
        _tagIntegerMap.put("gshh", Integer.valueOf(PhotoshopDirectory.TAG_JUMP_TO_XPEP));
        _tagIntegerMap.put("gspm", Integer.valueOf(PhotoshopDirectory.TAG_ALPHA_IDENTIFIERS));
        _tagIntegerMap.put("gspu", Integer.valueOf(PhotoshopDirectory.TAG_URL_LIST));
        _tagIntegerMap.put("gssd", Integer.valueOf(1055));
        _tagIntegerMap.put("gsst", Integer.valueOf(1056));
        _tagIntegerMap.put("gstd", Integer.valueOf(PhotoshopDirectory.TAG_VERSION));
        _tagIntegerMap.put("hdvd", Integer.valueOf(PhotoshopDirectory.TAG_EXIF_DATA_1));
        _tagIntegerMap.put("itnu", Integer.valueOf(PhotoshopDirectory.TAG_EXIF_DATA_3));
        _tagIntegerMap.put("keyw", Integer.valueOf(PhotoshopDirectory.TAG_XMP_DATA));
        _tagIntegerMap.put("ldes", Integer.valueOf(PhotoshopDirectory.TAG_CAPTION_DIGEST));
        _tagIntegerMap.put("pcst", Integer.valueOf(PhotoshopDirectory.TAG_PRINT_SCALE));
        _tagIntegerMap.put("perf", Integer.valueOf(1063));
        _tagIntegerMap.put("pgap", Integer.valueOf(PhotoshopDirectory.TAG_PIXEL_ASPECT_RATIO));
        _tagIntegerMap.put("plID", Integer.valueOf(PhotoshopDirectory.TAG_LAYER_COMPS));
        _tagIntegerMap.put("prID", Integer.valueOf(PhotoshopDirectory.TAG_ALTERNATE_DUOTONE_COLORS));
        _tagIntegerMap.put("purd", Integer.valueOf(PhotoshopDirectory.TAG_ALTERNATE_SPOT_COLORS));
        _tagIntegerMap.put("purl", Integer.valueOf(1068));
        _tagIntegerMap.put(ReactVideoViewManager.PROP_RATE, Integer.valueOf(PhotoshopDirectory.TAG_LAYER_SELECTION_IDS));
        _tagIntegerMap.put("rldt", Integer.valueOf(PhotoshopDirectory.TAG_HDR_TONING_INFO));
        _tagIntegerMap.put("rtng", Integer.valueOf(PhotoshopDirectory.TAG_PRINT_INFO));
        _tagIntegerMap.put("sfID", Integer.valueOf(PhotoshopDirectory.TAG_LAYER_GROUPS_ENABLED_ID));
        _tagIntegerMap.put("soaa", Integer.valueOf(PhotoshopDirectory.TAG_COLOR_SAMPLERS));
        _tagIntegerMap.put("soal", Integer.valueOf(PhotoshopDirectory.TAG_MEASUREMENT_SCALE));
        _tagIntegerMap.put("soar", Integer.valueOf(PhotoshopDirectory.TAG_TIMELINE_INFORMATION));
        _tagIntegerMap.put("soco", Integer.valueOf(PhotoshopDirectory.TAG_SHEET_DISCLOSURE));
        _tagIntegerMap.put("sonm", Integer.valueOf(PhotoshopDirectory.TAG_DISPLAY_INFO));
        _tagIntegerMap.put("sosn", Integer.valueOf(PhotoshopDirectory.TAG_ONION_SKINS));
        _tagIntegerMap.put("stik", Integer.valueOf(1079));
        _tagIntegerMap.put("titl", Integer.valueOf(PhotoshopDirectory.TAG_COUNT_INFORMATION));
        _tagIntegerMap.put("tmpo", Integer.valueOf(1081));
        _tagIntegerMap.put("trkn", Integer.valueOf(PhotoshopDirectory.TAG_PRINT_INFO_2));
        _tagIntegerMap.put("tven", Integer.valueOf(PhotoshopDirectory.TAG_PRINT_STYLE));
        _tagIntegerMap.put("tves", Integer.valueOf(PhotoshopDirectory.TAG_MAC_NSPRINTINFO));
        _tagIntegerMap.put("tvnn", Integer.valueOf(PhotoshopDirectory.TAG_WIN_DEVMODE));
        _tagIntegerMap.put("tvsh", Integer.valueOf(PhotoshopDirectory.TAG_AUTO_SAVE_FILE_PATH));
        _tagIntegerMap.put("tvsn", Integer.valueOf(PhotoshopDirectory.TAG_AUTO_SAVE_FORMAT));
        _tagIntegerMap.put("yrrc", Integer.valueOf(PhotoshopDirectory.TAG_PATH_SELECTION_STATE));
        _tagIntegerMap.put("�ART", Integer.valueOf(1089));
        _tagIntegerMap.put("�alb", Integer.valueOf(1090));
        _tagIntegerMap.put("�cmt", Integer.valueOf(1091));
        _tagIntegerMap.put("�com", Integer.valueOf(1092));
        _tagIntegerMap.put("�cpy", Integer.valueOf(1093));
        _tagIntegerMap.put("�day", Integer.valueOf(1094));
        _tagIntegerMap.put("�des", Integer.valueOf(1095));
        _tagIntegerMap.put("�enc", Integer.valueOf(1096));
        _tagIntegerMap.put("�gen", Integer.valueOf(1097));
        _tagIntegerMap.put("�grp", Integer.valueOf(1098));
        _tagIntegerMap.put("�lyr", Integer.valueOf(1099));
        _tagIntegerMap.put("�nam", Integer.valueOf(1100));
        _tagIntegerMap.put("�nrt", Integer.valueOf(1101));
        _tagIntegerMap.put("�pub", Integer.valueOf(1102));
        _tagIntegerMap.put("�too", Integer.valueOf(1103));
        _tagIntegerMap.put("�trk", Integer.valueOf(1104));
        _tagIntegerMap.put("�wrt", Integer.valueOf(1105));
        String str = "Album";
        _tagNameMap.put(valueOf, str);
        _tagNameMap.put(valueOf2, ExifInterface.TAG_ARTIST);
        _tagNameMap.put(valueOf3, "Artwork");
        _tagNameMap.put(valueOf4, "Author");
        _tagNameMap.put(valueOf5, "Comment");
        hashMap = _tagNameMap;
        String str2 = ExifInterface.TAG_COPYRIGHT;
        hashMap.put(valueOf6, str2);
        _tagNameMap.put(valueOf7, "Creation Date");
        String str3 = "Description";
        _tagNameMap.put(Integer.valueOf(OlympusCameraSettingsMakernoteDirectory.TagColorSpace), str3);
        _tagNameMap.put(Integer.valueOf(1288), "Director");
        String str4 = "Title";
        _tagNameMap.put(Integer.valueOf(OlympusCameraSettingsMakernoteDirectory.TagSceneMode), str4);
        String str5 = "Genre";
        _tagNameMap.put(Integer.valueOf(OlympusCameraSettingsMakernoteDirectory.TagNoiseReduction), str5);
        _tagNameMap.put(Integer.valueOf(OlympusCameraSettingsMakernoteDirectory.TagDistortionCorrection), "Information");
        _tagNameMap.put(Integer.valueOf(OlympusCameraSettingsMakernoteDirectory.TagShadingCompensation), "Keywords");
        _tagNameMap.put(Integer.valueOf(OlympusCameraSettingsMakernoteDirectory.TagCompressionFactor), "ISO 6709");
        _tagNameMap.put(Integer.valueOf(1294), "Producer");
        _tagNameMap.put(Integer.valueOf(OlympusCameraSettingsMakernoteDirectory.TagGradation), "Publisher");
        _tagNameMap.put(Integer.valueOf(1296), ExifInterface.TAG_SOFTWARE);
        _tagNameMap.put(Integer.valueOf(1297), "Year");
        _tagNameMap.put(Integer.valueOf(1298), "Collection User");
        _tagNameMap.put(Integer.valueOf(SonyType6MakernoteDirectory.TAG_MAKERNOTE_THUMB_OFFSET), "Rating User");
        _tagNameMap.put(Integer.valueOf(SonyType6MakernoteDirectory.TAG_MAKERNOTE_THUMB_LENGTH), "Location Name");
        _tagNameMap.put(Integer.valueOf(1301), "Location Body");
        _tagNameMap.put(Integer.valueOf(1302), "Location Note");
        _tagNameMap.put(Integer.valueOf(1303), "Location Role");
        _tagNameMap.put(Integer.valueOf(1304), "Location Date");
        _tagNameMap.put(Integer.valueOf(1305), "Direction Facing");
        _tagNameMap.put(Integer.valueOf(1306), "Direction Motion");
        _tagNameMap.put(Integer.valueOf(1307), "Display Name");
        _tagNameMap.put(Integer.valueOf(1308), "Content Identifier");
        _tagNameMap.put(Integer.valueOf(1309), ExifInterface.TAG_MAKE);
        _tagNameMap.put(Integer.valueOf(1310), ExifInterface.TAG_MODEL);
        _tagNameMap.put(Integer.valueOf(1311), "Originating Signature");
        _tagNameMap.put(Integer.valueOf(1024), "iTunes Info");
        _tagNameMap.put(Integer.valueOf(1025), "Parent Short Title");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_LAYERS_GROUP_INFORMATION), "Parent Product ID");
        _tagNameMap.put(Integer.valueOf(1027), "Parent Title");
        _tagNameMap.put(Integer.valueOf(1028), "Short Title");
        _tagNameMap.put(Integer.valueOf(1029), "Unknown_AACR?");
        _tagNameMap.put(Integer.valueOf(1030), "Unknown_CDEK?");
        _tagNameMap.put(Integer.valueOf(LeicaType5MakernoteDirectory.TagOriginalFileName), "Unknown_CDET?");
        _tagNameMap.put(Integer.valueOf(1032), "GUID");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_THUMBNAIL_OLD), "Product Version");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_COPYRIGHT), "Album Artist");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_URL), "Apple Store Account Type");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_THUMBNAIL), str);
        _tagNameMap.put(Integer.valueOf(1037), "Apple Store Account");
        _tagNameMap.put(Integer.valueOf(1038), "Album Title ID");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_ICC_PROFILE_BYTES), "Author");
        _tagNameMap.put(Integer.valueOf(1040), "Category");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_ICC_UNTAGGED_PROFILE), "Apple Store Catalog ID");
        _tagNameMap.put(Integer.valueOf(1042), "Cover Art");
        _tagNameMap.put(Integer.valueOf(1043), "Compilation");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_SEED_NUMBER), str2);
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_UNICODE_ALPHA_NAMES), str3);
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_INDEXED_COLOR_TABLE_COUNT), "Disk Number");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_TRANSPARENCY_INDEX), str3);
        _tagNameMap.put(Integer.valueOf(1048), "Episode Global Unique ID");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_GLOBAL_ALTITUDE), "Genre ID");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_SLICES), str5);
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_WORKFLOW_URL), "Grouping");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_JUMP_TO_XPEP), "Google Host Header");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_ALPHA_IDENTIFIERS), "Google Ping Message");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_URL_LIST), "Google Ping URL");
        _tagNameMap.put(Integer.valueOf(1055), "Google Source Data");
        _tagNameMap.put(Integer.valueOf(1056), "Google Start Time");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_VERSION), "Google Track Duration");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_EXIF_DATA_1), "HD Video");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_EXIF_DATA_3), "iTunes U");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_XMP_DATA), "Keyword");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_CAPTION_DIGEST), "Long Description");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_PRINT_SCALE), "Podcast");
        _tagNameMap.put(Integer.valueOf(1063), "Performer");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_PIXEL_ASPECT_RATIO), "Play Gap");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_LAYER_COMPS), "Play List ID");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_ALTERNATE_DUOTONE_COLORS), "Product ID");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_ALTERNATE_SPOT_COLORS), "Purchase Date");
        _tagNameMap.put(Integer.valueOf(1068), "Podcast URL");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_LAYER_SELECTION_IDS), "Rating Percent");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_HDR_TONING_INFO), "Release Date");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_PRINT_INFO), "Rating");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_LAYER_GROUPS_ENABLED_ID), "Apple Store Country");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_COLOR_SAMPLERS), "Sort Album Artist");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_MEASUREMENT_SCALE), "Sort Album");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_TIMELINE_INFORMATION), "Sort Artist");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_SHEET_DISCLOSURE), "Sort Composer");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_DISPLAY_INFO), "Sort Name");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_ONION_SKINS), "Sort Show");
        _tagNameMap.put(Integer.valueOf(1079), "Media Type");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_COUNT_INFORMATION), str4);
        _tagNameMap.put(Integer.valueOf(1081), "Beats Per Minute");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_PRINT_INFO_2), "Track Number");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_PRINT_STYLE), "TV Episode ID");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_MAC_NSPRINTINFO), "TV Episode");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_WIN_DEVMODE), "TV Network Name");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_AUTO_SAVE_FILE_PATH), "TV Show");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_AUTO_SAVE_FORMAT), "TV Season");
        _tagNameMap.put(Integer.valueOf(PhotoshopDirectory.TAG_PATH_SELECTION_STATE), "Year");
        _tagNameMap.put(Integer.valueOf(1089), ExifInterface.TAG_ARTIST);
        _tagNameMap.put(Integer.valueOf(1090), str);
        _tagNameMap.put(Integer.valueOf(1091), "Comment");
        _tagNameMap.put(Integer.valueOf(1092), "Composer");
        _tagNameMap.put(Integer.valueOf(1093), str2);
        _tagNameMap.put(Integer.valueOf(1094), "Content Create Date");
        _tagNameMap.put(Integer.valueOf(1095), str3);
        _tagNameMap.put(Integer.valueOf(1096), "Encoded By");
        _tagNameMap.put(Integer.valueOf(1097), str5);
        _tagNameMap.put(Integer.valueOf(1098), "Grouping");
        _tagNameMap.put(Integer.valueOf(1099), "Lyrics");
        _tagNameMap.put(Integer.valueOf(1100), str4);
        _tagNameMap.put(Integer.valueOf(1101), "Narrator");
        _tagNameMap.put(Integer.valueOf(1102), "Publisher");
        _tagNameMap.put(Integer.valueOf(1103), "Encoder");
        _tagNameMap.put(Integer.valueOf(1104), "Track");
        _tagNameMap.put(Integer.valueOf(1105), "Composer");
    }

    @NotNull
    protected HashMap<Integer, String> getTagNameMap() {
        return _tagNameMap;
    }
}
